// <auto-generated />
using System;
using Booking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712091241_AddAmenityToDb")]
    partial class AddAmenityToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date_19118162")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities", "19118162");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5064),
                            Name = "Private Pool",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5068),
                            Name = "Microwave",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5070),
                            Name = "Private Balcony",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5071),
                            Name = "1 king bed and 1 sofa bed",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5073),
                            Name = "Private Plunge Pool",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5075),
                            Name = "Microwave and Mini Refrigerator",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 7,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5077),
                            Name = "Private Balcony",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5079),
                            Name = "King bed or 2 double beds",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5080),
                            Name = "Private Pool",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 10,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5082),
                            Name = "Jacuzzi",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 11,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5084),
                            Name = "Private Balcony",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.Log_19118162", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log_19118162", "19118162");
                });

            modelBuilder.Entity("Booking.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_19118162")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas", "19118162");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(4731),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(4790),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(4792),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_19118162")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers", "19118162");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(4975),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(4977),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5023),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5025),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5027),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5029),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5030),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5032),
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            Date_19118162 = new DateTime(2024, 7, 12, 12, 12, 39, 274, DateTimeKind.Local).AddTicks(5033),
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("Booking.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("Booking.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("Booking.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
