// <auto-generated />
using System;
using Booking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711093447_addVillaNumber")]
    partial class addVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Entities.Log_19118162", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log_19118162", "19118162");
                });

            modelBuilder.Entity("Booking.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_19118162")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas", "19118162");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9766),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9823),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9825),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_19118162")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers", "19118162");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9899),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9902),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9904),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9906),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9907),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9909),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9911),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9912),
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            Date_19118162 = new DateTime(2024, 7, 11, 12, 34, 45, 555, DateTimeKind.Local).AddTicks(9914),
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("Booking.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
